- nvidia-bert/azureml-notebooks/run-pretraining.ipynb
Fixed project folder path in AML notebook
> Fixed project folder path in AML notebook

- nvidia-bert/README.md
- nvidia-bert/docker/Dockerfile
Fixed container image build from source.
> Updates to build-from-source

- nvidia-bert/README.md
Make it easier for user to know how to transfer data folder to blob storage. The portal and storage docs don't make clear how to transfer a folder.
> Provide sample command to upload training data

- nvidia-bert/ort_addon/run_pretraining_ort.py
- is_main_process() from NVIDIA utils.py only works with torch.distributed.
- causes race condition when saving checkpoint, leading to corruption in some cases.
- verified e2e on local and Azure run.
> Fix is_main_process() to use args.world_rank as determined in setup step

- README.md
Updated some language to make it less confusing.
> fixed language

- nvidia-bert/azureml-notebooks/run-pretraining.ipynb
- nvidia-bert/docker/Dockerfile
- nvidia-bert/ort_addon/ort_supplement/ort_supplement.py
- nvidia-bert/ort_addon/run_pretraining_ort.py
- nvidia-bert/ort_addon/scripts/run_pretraining_ort.sh
- Update to v2 API 
- Tested for phase 1 + 2 with checkpoint load on local Docker run and AML compute submission.
- Eliminate pytorch warning re: deprecation of torch.nonzero(...) without as_tuple flag.
> Revisions for v2 API

- nvidia-bert/azureml-notebooks/run-pretraining.ipynb
- nvidia-bert/docker/Dockerfile
- nvidia-bert/ort_addon/ort_supplement/ort_supplement.py
- nvidia-bert/ort_addon/run_pretraining_ort.py
Reverts microsoft/onnxruntime-training-examples#38
- References rc2 image or rc3 internal image will not work for public.
> Revert "Revisions for v2 API"

- getting-started/README.md
- getting-started/docker/Dockerfile
- getting-started/model.py
- getting-started/train_ort.py
Update Getting Started sample to new API
> Update API for Getting Started sample

- huggingface-gpt2/ort_addon/ort_supplement/src/transformers/trainer_ort.py
Fix the OOm issue for eval step, and loss logging. Also add some explanation in comments.
> GPT2 finetuning sample fixes

- .gitmodules
> Add huggingface-transformers as submodule

- README.md
- nvidia-bioBERT/README.md
- nvidia-bioBERT/azureml-notebooks/run-pretraining.ipynb
- nvidia-bioBERT/bertPrep.py
- nvidia-bioBERT/docker/Dockerfile
- nvidia-bioBERT/docker/build.sh
- nvidia-bioBERT/docker/launch.sh
- nvidia-bioBERT/ort_addon/convert_checkpoint.py
- nvidia-bioBERT/ort_addon/ort_supplement/azureml_adapter.py
- nvidia-bioBERT/ort_addon/ort_supplement/lr_schedules.py
- nvidia-bioBERT/ort_addon/ort_supplement/ort_supplement.py
- nvidia-bioBERT/ort_addon/run_pretraining_ort.py
- nvidia-bioBERT/ort_addon/scripts/run_pretraining_ort.sh
Added recipe for Bio BERT based on NVBERT Pytorch implementation.
> Bio bert sample

- huggingface/BART.md
- huggingface/BERT.md
- huggingface/DeBERTa.md
- huggingface/DistilBERT.md
- huggingface/GPT2.md
- huggingface/RoBERTa.md
- huggingface/T5.md
- huggingface/docker/Dockerfile
- huggingface/docker/Dockerfile-10.2
Without this change Bart-large was failing in https://github.com/microsoft/onnxruntime-training-examples with exception : "User program failed with AttributeError: module 'sacrebleu' has no attribute 'DEFAULT_TOKENIZER’ "
> Added sacrebleu version

- huggingface/README.md
* updated to direct users to use Python 3.8 rather than 3.6
* explained difference between regular Dockerfile and Dockerfile_clm for local runs
> Update README to reflect optimum submodule updates

- .gitignore
- distilbert-finetune/README.md
- distilbert-finetune/aml_submit.py
- distilbert-finetune/finetune-code/ds_config_zero_1.json
- distilbert-finetune/finetune-code/finetune.py
- distilbert-finetune/inference.py
- distilbert-finetune/ws_config.json
- distilbert-finetune/ws_config_template.json
moving code for youtube demo to this repository
> add code for youtube demo

- distilbert-finetune/score.py
This script is required for Parinita's UI demo. More details to come when official demos are publised.
> add scoring script for UI demo

- distilbert-finetune/aml_submit.py
- distilbert-finetune/finetune-code/finetune.py
- distilbert-finetune/inference_chat.py
adds a new example with a more "chat-like" ability as well as support for torch 2.0 (torch.compile)
> add inference chat

- QnA-finetune/aml_submit.py
- QnA-finetune/finetune-code/finetune.py
> add nebula checkpointing

- QnA-finetune/aml_submit.py
- QnA-finetune/finetune-code/finetune.py
> reset default model

- StableDiffusion-finetune/finetune-code/train_text_to_image.py
adds code to load a UNet trained via ONNX Runtime into a Stable Diffusion Pipeline
> add stable diffusion inference

- on_device_training/desktop/python/mnist.ipynb
Adding generate artifacts method to the docs
> add generate artifacts method to docs

- DragGAN/README.md
removed the duplicate C# section from the readme.md file
> removed the duplicate C# section from the readme.md file

- mistral-finetune/README.md
- mistral-finetune/aml_submit_clm.py
- mistral-finetune/environment/Dockerfile
- mistral-finetune/environment/requirements.txt
- mistral-finetune/finetune-clm/run_clm.py
- mistral-finetune/finetune-clm/zero_stage_2.json
- mistral-finetune/ws_config_template.json
Add Mistral finetune example for AI Dev
> add mistral finetune example

- mistral-finetune/README.md
- mistral-finetune/aml_submit_clm.py
- mistral-finetune/environment/requirements.txt
Update README for the mistral example and reduce max steps to 500
> update README and change max steps

- on_device_training/mobile/android/c-cpp/README.md
- on_device_training/mobile/android/java/README.md
Test the tutorial, fix it.
See also https://github.com/microsoft/onnxruntime/pull/18300.
> Improve tutorial Java / Android

- DragGAN/README.md
Blog came live - updating the link
> Blog came live - updating the link

- on_device_training/desktop/csharp/masked_language_modeling/mobilebert_offline.ipynb
Fix for issue https://github.com/microsoft/onnxruntime-training-examples/issues/176
thanks to @prathikr for the fix suggested here https://github.com/microsoft/onnxruntime/issues/19038
> added fix for gradientbuilderbase exception

- phi2-finetune/README.md
- phi2-finetune/aml_submit_clm.py
- phi2-finetune/environment/Dockerfile
- phi2-finetune/finetune-clm/run_clm.py
- phi2-finetune/finetune-clm/zero_stage_1.json
- phi2-finetune/finetune-clm/zero_stage_2.json
- phi2-finetune/ws_config_template.json
add phi2 finetune example for comparing PyTorch and ONNX Runtime performance
> add phi2 example

- on_device_training/web/web-bundler/src/App.css
- on_device_training/web/web-bundler/src/App.tsx
Added iterations per second calculations + table of memory usage.
Live preview of changes is available [here](https://carzh.github.io/onnxruntime-training-examples/)
> Add more metrics and information to E2E Web MNIST demo
